version: 2
jobs:
  build:
    working_directory: /go/src/github.com/moos3/flag-demo
    docker:
      - image: circleci/golang:1.11
    environment:
      - GOCACHE: "/tmp/go/cache"
      - DEP_VERSION: 0.4.1
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - restore_cache:
         keys:
          - v1-pkg-cache
       - run:
          name: download-libraries
          command: |
            if [ ! -d /go/src/github.com/moos3/flag-demo ]; then
                curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o /go/bin/dep
                chmod +x /go/bin/dep
                /go/bin/dep ensure
            fi
      - run:
          name: test
          command: |
            mkdir -p $GOCACHE
            go build -v
            go test -p 6 -race ./...
      - save_cache:
          key: build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
              - /tmp/go/cache